"""Slice 83 inventory payload (test-owned compact constants)."""

from __future__ import annotations

POST_FIX_MECHANISMS = "orm_add:102,orm_add+pg_insert:1,pg_insert:14,raw_insert:2"

_SPEC_TEXT = """\
app/admin/tenant_admin.py|49|_record_event|orm_add|tenant_admin_events
app/admin/tenant_admin.py|100|grant_admin_role|orm_add|admin_role_grants
app/agents/registry.py|136|register_blueprint|pg_insert|agent_blueprints
app/agents/registry.py|172|register_version|pg_insert|agent_versions
app/agents/registry.py|249|instantiate|orm_add|agent_instances
app/repositories/acceptance_verification.py|67|record_independent_approval|orm_add|acceptance_criterion_authorship_records
app/repositories/acceptance_verification.py|120|record_extraction_unapproved|orm_add|acceptance_criterion_authorship_records
app/repositories/acceptance_verification.py|161|record_dispute|orm_add|acceptance_criterion_authorship_records
app/repositories/acceptance_verification.py|206|record_failed_verification|orm_add|acceptance_verification_runs
app/repositories/acceptance_verification.py|338|verify_project|orm_add|acceptance_verification_results,acceptance_verification_runs
app/repositories/admin.py|58|record|orm_add|admin_actions
app/repositories/agent_failures.py|37|record_failure|orm_add|agent_failure_events
app/repositories/agent_realizations.py|30|realize|orm_add|agent_realization_reviewers,agent_realizations
app/repositories/api_keys.py|39|issue|orm_add|tenant_api_keys
app/repositories/approval_notifications.py|24|record|orm_add|approval_notifications
app/repositories/approvals.py|65|request|orm_add|approvals
app/repositories/approvals.py|308|_record|orm_add|approval_events
app/repositories/catalog_admin.py|71|register_connector|orm_add|catalog_assets,connector_catalog_specs,connector_catalog_tool_scope
app/repositories/catalog_admin.py|130|register_blueprint_version|orm_add|catalog_assets
app/repositories/catalog_admin.py|156|register_reference_intake|orm_add|catalog_assets
app/repositories/catalog_admin.py|211|record_contract_test|orm_add|catalog_vetting_check_results,catalog_vetting_records
app/repositories/catalog_admin.py|242|record_review|orm_add|catalog_vetting_records
app/repositories/catalog_admin.py|275|list_asset|orm_add|catalog_listings
app/repositories/catalog_adoptions.py|33|adopt|pg_insert|tenant_catalog_adoptions
app/repositories/ci_evidence.py|35|record_branch_protection|orm_add|branch_protection_snapshots
app/repositories/ci_evidence.py|60|record_connector_verified_branch_protection|orm_add|branch_protection_snapshots
app/repositories/classification.py|289|_record|orm_add|document_classifications
app/repositories/cost.py|47|record|orm_add+pg_insert|cost_events
app/repositories/cost.py|184|upsert|pg_insert|budgets
app/repositories/cost_forecast_persistence.py|45|_record_refusal|orm_add|cost_forecast_runs
app/repositories/cost_forecast_persistence.py|117|_persist_success|orm_add|cost_forecast_dimension_results,cost_forecast_input_lines,cost_forecast_ledger_event_refs,cost_forecast_runs
app/repositories/cost_forecasts.py|74|record_policy_version|pg_insert|cost_forecast_policy_versions
app/repositories/cost_optimizer.py|32|recommend|orm_add|cost_optimizer_citations,cost_optimizer_runs
app/repositories/deployments.py|48|_record|orm_add|deployment_target_snapshots
app/repositories/documents.py|36|ingest|pg_insert|documents
app/repositories/emergency_controls.py|337|append_binding|orm_add|emergency_control_authority_members,emergency_control_bindings,emergency_stop_events
app/repositories/emergency_controls.py|464|append_event|orm_add|emergency_stop_events
app/repositories/emergency_controls.py|494|activate|orm_add|emergency_stop_run_effects
app/repositories/emergency_controls.py|594|authorize_rollback|orm_add|emergency_rollback_authorizations
app/repositories/evidence_packs.py|79|record_audit_chain_verification|orm_add|audit_chain_verifications
app/repositories/evidence_packs.py|205|record_failed_attempt|orm_add|evidence_pack_generation_runs
app/repositories/evidence_packs.py|654|_persist_core|orm_add|evidence_pack_generation_runs,evidence_pack_section_results,evidence_pack_source_refs,evidence_packs
app/repositories/export_bundles.py|61|generate|orm_add|evidence_pack_export_files,evidence_pack_manifest_signatures
app/repositories/export_bundles.py|209|_try_insert_record|pg_insert|evidence_pack_export_records
app/repositories/extraction.py|62|extract|orm_add|extraction_proposals
app/repositories/extraction.py|295|_record_run|orm_add|extraction_runs
app/repositories/extraction_promotion.py|88|promote_proposal|orm_add|extraction_promotions,intake_artifacts
app/repositories/findings.py|44|evaluate_and_record|orm_add|intake_findings_reports
app/repositories/generator.py|333|_record|orm_add|generated_artifacts
app/repositories/go_live_decisions.py|177|start_cycle|pg_insert|control_loop_runs
app/repositories/go_live_decisions.py|291|append_event|orm_add|control_loop_events
app/repositories/go_live_decisions.py|338|record_evaluation|orm_add|go_live_evaluation_gate_results,go_live_evaluations
app/repositories/intake.py|37|add_artifact|orm_add|intake_artifacts,intake_provenance
app/repositories/intake_categories.py|35|declare|orm_add|intake_categories
app/repositories/learning.py|39|persist|orm_add|cross_project_aggregate_buckets,cross_project_aggregate_runs
app/repositories/monitoring_evidence.py|48|_record|orm_add|monitoring_status_snapshots
app/repositories/ops_hotfix.py|252|_try_insert_run|pg_insert|ops_self_healing_runs
app/repositories/ops_hotfix.py|297|_insert_plans|orm_add|ops_hotfix_plans
app/repositories/ops_hotfix.py|327|_insert_children|orm_add|ops_self_healing_results
app/repositories/ops_incidents.py|119|try_insert_incident|pg_insert|ops_incidents
app/repositories/ops_incidents.py|150|_insert_ticket|orm_add|ops_incident_tickets
app/repositories/ops_incidents.py|167|_append_event|orm_add|ops_incident_events
app/repositories/ops_incidents.py|177|insert_evaluation|orm_add|ops_incident_action_evaluations,ops_incident_action_results
app/repositories/ops_incidents.py|371|record_handover|orm_add|ops_support_handovers
app/repositories/ops_signals.py|154|try_insert_run|pg_insert|ops_observation_runs
app/repositories/ops_signals.py|191|insert_results|orm_add|ops_signal_results
app/repositories/ops_stabilization.py|159|attempt_closure|orm_add|ops_stabilization_closure_attempts
app/repositories/ops_stabilization.py|291|_try_insert_window|pg_insert|ops_stabilization_windows
app/repositories/ops_stabilization.py|349|_insert_children|orm_add|ops_improvement_results,ops_stabilization_criterion_results
app/repositories/pm_issues.py|43|_record|orm_add|pm_issue_mappings
app/repositories/pr_evidence.py|68|_record|orm_add|pull_request_evidence_snapshots
app/repositories/production_preapprovals.py|248|append_policy_snapshot|orm_add|production_approval_policy_approvers,production_approval_policy_versions
app/repositories/production_preapprovals.py|288|append_request|orm_add|production_preapproval_requests
app/repositories/production_preapprovals.py|403|append_attestation|orm_add|production_preapproval_attestations
app/repositories/production_preapprovals.py|440|append_lifecycle_event|orm_add|production_preapproval_lifecycle_events
app/repositories/projects.py|12|create|orm_add|projects
app/repositories/qualification.py|74|record_qualification_run|orm_add|qualification_case_results,qualification_runs
app/repositories/readiness.py|108|evaluate_and_record|orm_add|readiness_reports
app/repositories/release_candidates.py|32|create|orm_add|release_candidates
app/repositories/release_candidates.py|64|bind_issue|orm_add|release_candidate_issue_bindings
app/repositories/release_candidates.py|267|_event|orm_add|release_candidate_events
app/repositories/release_findings.py|28|create|orm_add|release_findings
app/repositories/release_findings.py|136|_event|orm_add|release_finding_events
app/repositories/release_issues.py|42|create|orm_add|release_issues
app/repositories/release_issues.py|62|create_from_trusted_finding|orm_add|release_issues
app/repositories/release_issues.py|256|_event|orm_add|release_issue_events
app/repositories/release_verdicts.py|245|evaluate_and_record|orm_add|release_verdict_issue_results,release_verdict_runs,release_verdicts
app/repositories/release_verdicts.py|399|record_failed_attempt|orm_add|release_verdict_runs
app/repositories/review_reports.py|32|record_report|orm_add|review_reports
app/repositories/reviewer_quality.py|106|execute_suite|orm_add|reviewer_quality_records
app/repositories/reviewer_quality.py|337|_record_case|orm_add|reviewer_quality_case_results,reviewer_quality_defect_results
app/repositories/reviewer_quality.py|383|_failure|orm_add|reviewer_quality_records
app/repositories/risk_acceptance.py|42|create|orm_add|risk_acceptance_records
app/repositories/risk_acceptance.py|223|_event|orm_add|risk_acceptance_events
app/repositories/rollback_verifications.py|273|_record_failure|orm_add|rollback_verification_runs
app/repositories/rollback_verifications.py|301|_record_observation|orm_add|rollback_verification_phase_results,rollback_verification_runs
app/repositories/runs.py|66|record_step|orm_add|run_steps
app/repositories/secrets_verification.py|47|_record|orm_add|secret_reference_checks
app/repositories/security_scans.py|117|_record_failure|orm_add|security_scan_runs
app/repositories/security_scans.py|148|_record_observation|orm_add|security_scan_runs
app/repositories/security_scans.py|180|_record_category|orm_add|release_finding_events,release_findings,security_scan_category_results
app/repositories/semantic_contradictions.py|243|_record|orm_add|semantic_contradiction_reports,semantic_contradictions
app/repositories/shortcut_detectors.py|345|_record_failure|orm_add|shortcut_detector_runs
app/repositories/shortcut_detectors.py|380|_record_success|orm_add|release_finding_events,release_findings,shortcut_detector_category_results,shortcut_detector_reviewer_results,shortcut_detector_runs
app/repositories/skills.py|40|register_skill|raw_insert|skills
app/repositories/skills.py|52|register_capability|raw_insert|agent_provided_skills,agent_skill_capabilities
app/repositories/skills.py|178|build_and_record|orm_add|skill_matches,squad_manifests
app/repositories/task_contracts.py|53|create|orm_add|task_contract_events,task_contracts
app/repositories/task_contracts.py|129|add_artifact_link|orm_add|task_contract_artifact_links
app/repositories/task_contracts.py|178|add_reviewer|orm_add|task_contract_reviewers
app/repositories/task_contracts.py|256|_transition|orm_add|task_contract_events
app/repositories/test_oracles.py|364|_record_failure|orm_add|test_oracle_runs
app/repositories/test_oracles.py|623|_record_judgment_success|orm_add|test_oracle_runs,test_results
app/repositories/test_oracles.py|691|_record_deterministic_success|orm_add|test_oracle_runs,test_results
app/repositories/tools.py|46|_event|orm_add|agent_tool_allowlist
app/repositories/tools.py|69|record|orm_add|tool_calls
app/runtime/checkpointer.py|81|aput|pg_insert|run_checkpoints
app/runtime/checkpointer.py|122|aput_writes|pg_insert|run_checkpoint_writes
app/tenancy.py|96|add|orm_add|admin_actions,agent_instances,agent_tool_allowlist,approval_events,approvals,evidence_pack_export_files,evidence_pack_manifest_signatures,ops_hotfix_plans,ops_improvement_results,ops_incident_action_evaluations,ops_incident_action_results,ops_incident_events,ops_incident_tickets,ops_self_healing_results,ops_stabilization_closure_attempts,ops_stabilization_criterion_results,ops_support_handovers,projects,run_steps,tool_calls
app/audit.py|30|audit_append|sql_function_wrapper|audit_logs
app/repositories/admin.py|91|admin_write_autonomy_policy|sql_function_wrapper|admin_policy_changes,autonomy_policies
app/repositories/go_live_decisions.py|443|slice55_finalize_decision|sql_function_wrapper|go_live_decisions
"""

_COLL_TEXT = """\
acceptance_criterion_authorship_records|uq_acar_criterion_sequence,uq_acar_supersedes_once
acceptance_verification_results|uq_avres_run_criterion
admin_policy_changes|uq_admin_policy_changes_action
admin_role_grants|uq_admin_role_grants_tenant_id_principal_subject_admin_role
agent_blueprints|uq_agent_blueprints_key
agent_instances|uq_agent_instances_live_key
agent_provided_skills|uq_aps_capability_skill
agent_realization_reviewers|uq_agent_realization_reviewers_pair
agent_realizations|uq_agent_realizations_instance
agent_versions|uq_agent_versions_blueprint_id_version_label,uq_agent_versions_content_hash
audit_logs|uq_audit_logs_entry_hash,uq_audit_logs_seq
autonomy_policies|uq_autonomy_policies_tenant_id_project_id
budgets|uq_budgets_tenant_id_project_id
catalog_assets|uq_ca_kind_key_version
catalog_listings|uq_cl_live_asset
catalog_vetting_check_results|uq_cvcr_record_name
connector_catalog_specs|uq_ccs_asset_id
connector_catalog_tool_scope|uq_ccts_asset_tool
control_loop_events|uq_cle_loop_root,uq_cle_previous,uq_cle_run_ordinal
control_loop_runs|uq_clr_idempotency
cost_events|uq_cost_events_idempotency
cost_forecast_dimension_results|uq_cfdr_run_dimension,uq_cfdr_run_ordinal
cost_forecast_input_lines|uq_cfil_run_kind_component,uq_cfil_run_model_route,uq_cfil_run_ordinal
cost_forecast_ledger_event_refs|uq_cfler_run_event,uq_cfler_run_ordinal
cost_forecast_policy_versions|uq_cfpv_project_digest
cost_optimizer_citations|uq_coc_run_bucket
cross_project_aggregate_buckets|uq_cpab_run_class_key
documents|uq_documents_content
emergency_control_authority_members|uq_ecam_binding_ordinal,uq_ecam_binding_subject
emergency_control_bindings|uq_ecb_idempotency
emergency_rollback_authorizations|uq_era_idempotency
emergency_stop_events|uq_ese_idempotency,uq_ese_previous,uq_ese_project_root
emergency_stop_run_effects|uq_esre_event_run
evidence_pack_export_files|uq_epef_file_name,uq_epef_ordinal
evidence_pack_export_records|uq_epr_idempotency
evidence_pack_manifest_signatures|uq_epms_export_record
evidence_pack_section_results|uq_eps_pack_ordinal,uq_eps_pack_section
evidence_pack_source_refs|uq_epsr_pack_ordinal,uq_epsr_pack_source
evidence_packs|uq_evidence_packs_generation_run
extraction_promotions|uq_extraction_promotions_proposal
go_live_decisions|uq_gld_entry_hash,uq_gld_evaluation,uq_gld_previous,uq_gld_project_root
go_live_evaluation_gate_results|uq_glegr_gate,uq_glegr_ordinal
go_live_evaluations|uq_gle_loop
intake_artifacts|uq_intake_artifacts_ref
intake_categories|uq_intake_categories_cat
ops_hotfix_plans|uq_ops_hotfix_plans_run_kind
ops_improvement_results|uq_ops_improvement_results_window_seq
ops_incident_action_results|uq_ops_incident_action_results_eval_action,uq_ops_incident_action_results_eval_seq
ops_incident_tickets|uq_ops_incident_tickets_incident
ops_incidents|uq_ops_incidents_idempotency
ops_observation_runs|uq_ops_observation_runs_idempotency
ops_self_healing_results|uq_ops_self_healing_results_run_action,uq_ops_self_healing_results_run_seq
ops_self_healing_runs|uq_ops_self_healing_runs_idempotency
ops_signal_results|uq_ops_signal_results_run_class,uq_ops_signal_results_run_seq
ops_stabilization_criterion_results|uq_ops_stab_criteria_window_seq
ops_stabilization_windows|uq_ops_stab_windows_idempotency
production_approval_policy_approvers|uq_papa_policy_ordinal,uq_papa_policy_subject
production_preapproval_attestations|uq_ppa_idempotency,uq_ppa_request
production_preapproval_lifecycle_events|uq_pple_attestation_event,uq_pple_idempotency,uq_pple_previous
production_preapproval_requests|uq_ppr_generic_approval,uq_ppr_idempotency
projects|uq_projects_tenant_id_slug
release_candidate_issue_bindings|uq_release_candidate_issue_binding
release_candidates|uq_release_candidates_ref
release_findings|uq_release_findings_scan_fingerprint,uq_release_findings_shortcut_fingerprint
release_issues|uq_release_issues_source_finding
release_verdict_issue_results|uq_rvir_verdict_binding,uq_rvir_verdict_ordinal
release_verdicts|uq_release_verdicts_run
reviewer_quality_case_results|uq_rqcr_record_case
reviewer_quality_defect_results|uq_rqdr_case_defect
rollback_verification_phase_results|uq_rvpr_run_ordinal,uq_rvpr_run_phase
run_checkpoint_writes|uq_run_checkpoint_writes_id
run_checkpoints|uq_run_checkpoints_id
security_scan_category_results|uq_sscr_run_category
shortcut_detector_category_results|uq_sdcr_run_category
shortcut_detector_reviewer_results|uq_sdrr_category_reviewer
skills|uq_skills_key
task_contract_artifact_links|uq_tc_artifact_links_triple
task_contract_reviewers|uq_tc_reviewers_registration,uq_tc_reviewers_triple
task_contracts|uq_task_contracts_ref
tenant_api_keys|uq_tenant_api_keys_key_hash
tenant_catalog_adoptions|uq_tca_tenant_project_listing
test_results|uq_test_results_deterministic_case,uq_test_results_judgment_vote
"""

_PENDING_TEXT = """\
acceptance_verification_results.uq_avres_run_criterion
admin_role_grants.uq_admin_role_grants_tenant_id_principal_subject_admin_role
agent_instances.uq_agent_instances_live_key
agent_provided_skills.uq_aps_capability_skill
agent_realizations.uq_agent_realizations_instance
catalog_assets.uq_ca_kind_key_version
catalog_listings.uq_cl_live_asset
catalog_vetting_check_results.uq_cvcr_record_name
connector_catalog_specs.uq_ccs_asset_id
control_loop_runs.uq_clr_idempotency
cost_events.uq_cost_events_idempotency
cost_forecast_dimension_results.uq_cfdr_run_dimension
cost_forecast_dimension_results.uq_cfdr_run_ordinal
cost_forecast_input_lines.uq_cfil_run_kind_component
cost_forecast_input_lines.uq_cfil_run_model_route
cost_forecast_input_lines.uq_cfil_run_ordinal
cost_forecast_ledger_event_refs.uq_cfler_run_event
cost_forecast_ledger_event_refs.uq_cfler_run_ordinal
cost_optimizer_citations.uq_coc_run_bucket
cross_project_aggregate_buckets.uq_cpab_run_class_key
documents.uq_documents_content
emergency_control_authority_members.uq_ecam_binding_ordinal
emergency_control_authority_members.uq_ecam_binding_subject
emergency_control_bindings.uq_ecb_idempotency
emergency_rollback_authorizations.uq_era_idempotency
emergency_stop_run_effects.uq_esre_event_run
evidence_pack_export_files.uq_epef_file_name
evidence_pack_export_files.uq_epef_ordinal
evidence_pack_export_records.uq_epr_idempotency
evidence_pack_manifest_signatures.uq_epms_export_record
evidence_pack_section_results.uq_eps_pack_ordinal
evidence_pack_section_results.uq_eps_pack_section
evidence_pack_source_refs.uq_epsr_pack_ordinal
evidence_pack_source_refs.uq_epsr_pack_source
evidence_packs.uq_evidence_packs_generation_run
extraction_promotions.uq_extraction_promotions_proposal
go_live_evaluation_gate_results.uq_glegr_gate
go_live_evaluation_gate_results.uq_glegr_ordinal
go_live_evaluations.uq_gle_loop
intake_categories.uq_intake_categories_cat
ops_hotfix_plans.uq_ops_hotfix_plans_run_kind
ops_improvement_results.uq_ops_improvement_results_window_seq
ops_incident_action_results.uq_ops_incident_action_results_eval_action
ops_incident_action_results.uq_ops_incident_action_results_eval_seq
ops_incident_tickets.uq_ops_incident_tickets_incident
ops_incidents.uq_ops_incidents_idempotency
ops_observation_runs.uq_ops_observation_runs_idempotency
ops_self_healing_results.uq_ops_self_healing_results_run_action
ops_self_healing_results.uq_ops_self_healing_results_run_seq
ops_self_healing_runs.uq_ops_self_healing_runs_idempotency
ops_signal_results.uq_ops_signal_results_run_class
ops_signal_results.uq_ops_signal_results_run_seq
ops_stabilization_criterion_results.uq_ops_stab_criteria_window_seq
ops_stabilization_windows.uq_ops_stab_windows_idempotency
production_approval_policy_approvers.uq_papa_policy_ordinal
production_approval_policy_approvers.uq_papa_policy_subject
production_preapproval_attestations.uq_ppa_idempotency
production_preapproval_attestations.uq_ppa_request
production_preapproval_requests.uq_ppr_generic_approval
production_preapproval_requests.uq_ppr_idempotency
projects.uq_projects_tenant_id_slug
release_candidate_issue_bindings.uq_release_candidate_issue_binding
release_candidates.uq_release_candidates_ref
release_findings.uq_release_findings_scan_fingerprint
release_findings.uq_release_findings_shortcut_fingerprint
release_issues.uq_release_issues_source_finding
release_verdict_issue_results.uq_rvir_verdict_binding
release_verdict_issue_results.uq_rvir_verdict_ordinal
release_verdicts.uq_release_verdicts_run
reviewer_quality_case_results.uq_rqcr_record_case
reviewer_quality_defect_results.uq_rqdr_case_defect
rollback_verification_phase_results.uq_rvpr_run_ordinal
rollback_verification_phase_results.uq_rvpr_run_phase
run_checkpoints.uq_run_checkpoints_id
security_scan_category_results.uq_sscr_run_category
shortcut_detector_category_results.uq_sdcr_run_category
shortcut_detector_reviewer_results.uq_sdrr_category_reviewer
skills.uq_skills_key
task_contract_artifact_links.uq_tc_artifact_links_triple
task_contract_reviewers.uq_tc_reviewers_registration
task_contract_reviewers.uq_tc_reviewers_triple
task_contracts.uq_task_contracts_ref
tenant_api_keys.uq_tenant_api_keys_key_hash
test_results.uq_test_results_deterministic_case
test_results.uq_test_results_judgment_vote
"""

_NODE_TEXT = """\
budgets.uq_budgets_tenant_id_project_id|tests/test_slice83_races_core.py::test_p_green_1_budget_upsert_first_write
agent_blueprints.uq_agent_blueprints_key|tests/test_slice83_races_core.py::test_p_green_2_register_blueprint_first_write
agent_versions.uq_agent_versions_content_hash|tests/test_slice83_races_core.py::test_p_green_3a_register_version_identical_content
agent_versions.uq_agent_versions_blueprint_id_version_label|tests/test_slice83_races_core_b.py::test_p_green_3b_version_label_conflict
tenant_catalog_adoptions.uq_tca_tenant_project_listing|tests/test_slice83_races_core.py::test_p_green_4_catalog_adopt_first_write
cost_forecast_policy_versions.uq_cfpv_project_digest|tests/test_slice83_races_core.py::test_p_green_5_forecast_policy_version_first_write
intake_artifacts.uq_intake_artifacts_ref|tests/test_slice83_races_core.py::test_p_green_6a_promote_proposal_first_write
autonomy_policies.uq_autonomy_policies_tenant_id_project_id|tests/test_admin_policy_race_db.py::test_p_writer_concurrent_first_write|tests/test_admin_policy_race_db.py::test_p_writer_concurrent_first_write_mutation
acceptance_criterion_authorship_records.uq_acar_criterion_sequence|tests/test_slice83_a1_races.py::test_a1_acceptance_first_write_green|tests/test_slice83_a1_races.py::test_a1_acceptance_sequence_mutation
acceptance_criterion_authorship_records.uq_acar_supersedes_once|tests/test_slice83_a1_races.py::test_a1_acceptance_supersedes_green|tests/test_slice83_a1_races.py::test_a1_acceptance_supersedes_mutation
control_loop_events.uq_cle_run_ordinal|tests/test_slice83_a1_races.py::test_a1_control_loop_first_event_green|tests/test_slice83_a1_races.py::test_a1_control_loop_ordinal_mutation
control_loop_events.uq_cle_loop_root|tests/test_slice83_a1_races.py::test_a1_control_loop_first_event_green|tests/test_slice83_a1_races.py::test_a1_control_loop_root_mutation
control_loop_events.uq_cle_previous|tests/test_slice83_a1_races.py::test_a1_control_loop_previous_green|tests/test_slice83_a1_races.py::test_a1_control_loop_previous_mutation
emergency_stop_events.uq_ese_project_root|tests/test_slice83_a1_races_b.py::test_a1_emergency_project_root_green|tests/test_slice83_a1_races_b.py::test_a1_emergency_project_root_mutation
production_preapproval_lifecycle_events.uq_pple_previous|tests/test_slice83_a1_races_b.py::test_a1_preapproval_revoke_green|tests/test_slice83_a1_races_b.py::test_a1_preapproval_previous_mutation
production_preapproval_lifecycle_events.uq_pple_attestation_event|tests/test_slice83_a1_races_b.py::test_a1_preapproval_revoke_green|tests/test_slice83_a1_races_b.py::test_a1_preapproval_attestation_event_mutation
production_preapproval_lifecycle_events.uq_pple_idempotency|tests/test_slice83_a1_races_b.py::test_a1_preapproval_revoke_green|tests/test_slice83_a1_races_b.py::test_a1_preapproval_idempotency_mutation
admin_policy_changes.uq_admin_policy_changes_action|tests/test_slice83_a1_ledger.py::test_a1_admin_policy_change_green|tests/test_slice83_a1_ledger.py::test_a1_admin_policy_change_mutation
audit_logs.uq_audit_logs_seq|tests/test_slice83_a1_ledger.py::test_a1_audit_append_green|tests/test_slice83_a1_ledger.py::test_a1_audit_append_mutation
audit_logs.uq_audit_logs_entry_hash|tests/test_slice83_a1_ledger.py::test_a1_audit_append_green|tests/test_slice83_a1_ledger.py::test_a1_audit_append_mutation
emergency_stop_events.uq_ese_previous|tests/test_slice83_a1_ledger_b.py::test_a1_emergency_activate_previous_green|tests/test_slice83_a1_ledger_b.py::test_a1_emergency_activate_previous_mutation
emergency_stop_events.uq_ese_idempotency|tests/test_slice83_a1_ledger_b.py::test_a1_emergency_activate_idempotency_green|tests/test_slice83_a1_ledger_b.py::test_a1_emergency_activate_idempotency_mutation
go_live_decisions.uq_gld_project_root|tests/test_slice83_a1_ledger_b.py::test_a1_gld_first_write_green|tests/test_slice83_a1_ledger_b.py::test_a1_gld_project_root_mutation
go_live_decisions.uq_gld_entry_hash|tests/test_slice83_a1_ledger_b.py::test_a1_gld_first_write_green|tests/test_slice83_a1_ledger_b.py::test_a1_gld_hash_mutation
go_live_decisions.uq_gld_previous|tests/test_slice83_a1_ledger_b.py::test_a1_gld_previous_green|tests/test_slice83_a1_ledger_b.py::test_a1_gld_previous_mutation
go_live_decisions.uq_gld_evaluation|tests/test_slice83_a1_ledger_b.py::test_a1_gld_evaluation_green|tests/test_slice83_a1_ledger_b.py::test_a1_gld_evaluation_mutation
run_checkpoint_writes.uq_run_checkpoint_writes_id|tests/test_slice83_a1_ledger.py::test_a1_checkpoint_writes_green|tests/test_slice83_a1_ledger.py::test_a1_checkpoint_writes_mutation
"""

_B2_TEXT = """\
agent_realization_reviewers.uq_agent_realization_reviewers_pair|agent_realizations|realization_id|agent_realizations.uq_agent_realizations_instance|app/repositories/agent_realizations.py:63
connector_catalog_tool_scope.uq_ccts_asset_tool|catalog_assets|asset_id|catalog_assets.uq_ca_kind_key_version|app/repositories/catalog_admin.py:108
"""

SERIALIZABLE_TABLE = "go_live_decisions"
SERIALIZABLE_CITATION = "app/repositories/go_live_decisions.py:445"
RETRYABLE = ("40001", "40P01")


def _split_tables(raw: str) -> tuple[str, ...]:
    return tuple(raw.split(",")) if raw else ()


SPECS: tuple[tuple[str, int, str, str, tuple[str, ...]], ...] = tuple(
    (
        path,
        int(lineno),
        name,
        mech,
        _split_tables(tables),
    )
    for path, lineno, name, mech, tables in (
        line.split("|", 4) for line in _SPEC_TEXT.splitlines() if line
    )
)

COLLIDABLE: dict[str, tuple[str, ...]] = {
    table: _split_tables(indexes)
    for table, indexes in (line.split("|", 1) for line in _COLL_TEXT.splitlines() if line)
}

B2_META: dict[str, tuple[str, str, str, str]] = {
    leaf: (parent, fk, parent_leaf, citation)
    for leaf, parent, fk, parent_leaf, citation in (
        line.split("|", 4) for line in _B2_TEXT.splitlines() if line
    )
}

TIER_A_NODE_MAP: dict[str, tuple[str, ...]] = {
    leaf: tuple(nodes)
    for leaf, *nodes in (line.split("|") for line in _NODE_TEXT.splitlines() if line)
}

PENDING_TIER_A_BATCHES: frozenset[str] = frozenset(
    line for line in _PENDING_TEXT.splitlines() if line
)
