"""approvals

Revision ID: 0005
Revises: 0004
Create Date: 2026-06-03

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("subject_ref", sa.Text(), nullable=True),
        sa.Column("risk_tier", sa.Text(), nullable=False),
        sa.Column("requires_explicit_approval", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("requested_by", sa.Text(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "approver_provenance",
            sa.Text(),
            server_default=sa.text("'caller_supplied_unverified'"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "risk_tier IN ('low', 'medium', 'high', 'production')",
            name=op.f("ck_approvals_risk_tier_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'cancelled', 'expired', 'proceeded_by_policy')",
            name=op.f("ck_approvals_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_approvals_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_approvals_id_tenant_id")),
    )
    op.create_index(op.f("ix_approvals_tenant_id"), "approvals", ["tenant_id"], unique=False)
    op.create_index(
        "ix_approvals_tenant_id_status", "approvals", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "approval_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("approval_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('requested', 'approved', 'rejected', 'cancelled', 'expired', 'proceeded_by_policy')",
            name=op.f("ck_approval_events_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_id", "tenant_id"],
            ["approvals.id", "approvals.tenant_id"],
            name="approval_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_approval_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_events")),
    )
    op.create_index(
        op.f("ix_approval_events_approval_id"), "approval_events", ["approval_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_events_tenant_id"), "approval_events", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Row-level security (deny-by-default; mirrors 0002/0004) on both tables.
    for table in ("approvals", "approval_events"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
        )
    # Governance grants: approvals are updatable (status transitions) but never
    # deletable; approval_events are append-only.
    op.execute("GRANT SELECT, INSERT, UPDATE ON approvals TO uaid_app")
    op.execute("GRANT SELECT, INSERT ON approval_events TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT ON approval_events FROM uaid_app")
    op.execute("REVOKE SELECT, INSERT, UPDATE ON approvals FROM uaid_app")
    for table in ("approval_events", "approvals"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_events_tenant_id"), table_name="approval_events")
    op.drop_index(op.f("ix_approval_events_approval_id"), table_name="approval_events")
    op.drop_table("approval_events")
    op.drop_index("ix_approvals_tenant_id_status", table_name="approvals")
    op.drop_index(op.f("ix_approvals_tenant_id"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
