"""tool_broker

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-03

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tool_allowlist",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('grant', 'revoke')",
            name=op.f("ck_agent_tool_allowlist_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agent_tool_allowlist_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_allowlist")),
    )
    op.create_index(
        "ix_agent_tool_allowlist_lookup",
        "agent_tool_allowlist",
        ["tenant_id", "agent_id", "tool_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tool_allowlist_tenant_id"),
        "agent_tool_allowlist",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column(
            "agent_provenance",
            sa.Text(),
            server_default=sa.text("'caller_supplied_unverified'"),
            nullable=False,
        ),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('allowed_unverified_identity', 'needs_approval', 'needs_authenticated_approval', 'denied_unknown_tool', 'denied_invalid_params', 'denied_not_allowlisted', 'denied_policy')",
            name=op.f("ck_tool_calls_decision_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tool_calls_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    op.create_index(op.f("ix_tool_calls_tenant_id"), "tool_calls", ["tenant_id"], unique=False)
    op.create_index(
        "ix_tool_calls_tenant_id_created_at",
        "tool_calls",
        ["tenant_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Row-level security (deny-by-default; mirrors 0002/0004/0005) on both tables.
    for table in ("tool_calls", "agent_tool_allowlist"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
        )
    # Append-only: SELECT + INSERT only (no UPDATE/DELETE on either table).
    op.execute("GRANT SELECT, INSERT ON tool_calls TO uaid_app")
    op.execute("GRANT SELECT, INSERT ON agent_tool_allowlist TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT ON agent_tool_allowlist FROM uaid_app")
    op.execute("REVOKE SELECT, INSERT ON tool_calls FROM uaid_app")
    for table in ("tool_calls", "agent_tool_allowlist"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_calls_tenant_id_created_at", table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tenant_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_agent_tool_allowlist_tenant_id"), table_name="agent_tool_allowlist")
    op.drop_index("ix_agent_tool_allowlist_lookup", table_name="agent_tool_allowlist")
    op.drop_table("agent_tool_allowlist")
    # ### end Alembic commands ###
