"""agent_registry

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-03

Global agent_blueprints + immutable agent_versions (admin-curated, uaid_app
SELECT-only) and tenant-owned agent_instances (RLS). agent_versions is immutable
via UPDATE/DELETE/TRUNCATE triggers (§9.7); agent_instances binding columns are
immutable and active_run_id is set-once via an UPDATE trigger.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_blueprints",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("mission", sa.String(), nullable=False),
        sa.Column("archetype", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default=sa.text("'active'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'deprecated')",
            name=op.f("ck_agent_blueprints_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_blueprints")),
        sa.UniqueConstraint("key", name=op.f("uq_agent_blueprints_key")),
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("version_label", sa.String(), nullable=False),
        sa.Column("model_route", sa.String(), nullable=False),
        sa.Column("prompt_hash", sa.String(), nullable=False),
        sa.Column("tool_policy_hash", sa.String(), nullable=False),
        sa.Column("context_policy_hash", sa.String(), nullable=False),
        sa.Column("eval_suite_hash", sa.String(), nullable=False),
        sa.Column("critical_dependencies_hash", sa.String(), nullable=False),
        sa.Column("output_schema_hash", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blueprint_id"],
            ["agent_blueprints.id"],
            name=op.f("fk_agent_versions_blueprint_id_agent_blueprints"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint(
            "blueprint_id",
            "version_label",
            name=op.f("uq_agent_versions_blueprint_id_version_label"),
        ),
        sa.UniqueConstraint("content_hash", name=op.f("uq_agent_versions_content_hash")),
    )
    # Must exist BEFORE agent_instances' triple composite FK references it.
    op.create_unique_constraint(
        op.f("uq_project_runs_id_project_id_tenant_id"),
        "project_runs",
        ["id", "project_id", "tenant_id"],
    )
    op.create_table(
        "agent_instances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("instance_key", sa.String(), nullable=False),
        sa.Column("active_run_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'registered'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('registered', 'active', 'suspended', 'retired')",
            name=op.f("ck_agent_instances_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["active_run_id", "project_id", "tenant_id"],
            ["project_runs.id", "project_runs.project_id", "project_runs.tenant_id"],
            name="run_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agent_instances_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_instances_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_instances")),
    )
    op.create_index(
        op.f("ix_agent_instances_tenant_id"), "agent_instances", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_agent_instances_live_key",
        "agent_instances",
        ["tenant_id", "project_id", "instance_key"],
        unique=True,
        postgresql_where=sa.text("status IN ('registered', 'active', 'suspended')"),
    )
    # ### end Alembic commands ###

    # --- agent_versions immutability (§9.7): block UPDATE/DELETE/TRUNCATE -------
    # DB-enforced for ordinary DML against ALL roles incl. the table owner; a DB
    # superuser/schema owner can still DISABLE TRIGGER or drop the table via
    # privileged paths (tamper-resistant for DML, not tamper-proof).
    op.execute(
        """
        CREATE FUNCTION public.agent_versions_block_mutation() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
        BEGIN
            RAISE EXCEPTION 'agent_versions is immutable (no UPDATE/DELETE/TRUNCATE)';
        END
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER agent_versions_no_update_delete
            BEFORE UPDATE OR DELETE ON public.agent_versions
            FOR EACH ROW EXECUTE FUNCTION public.agent_versions_block_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER agent_versions_no_truncate
            BEFORE TRUNCATE ON public.agent_versions
            FOR EACH STATEMENT EXECUTE FUNCTION public.agent_versions_block_mutation()
        """
    )

    # --- agent_instances binding immutability: identity columns frozen, --------
    #     active_run_id set-once (NULL -> value; no rebinding to a different run).
    op.execute(
        """
        CREATE FUNCTION public.agent_instances_block_rebind() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
        BEGIN
            IF NEW.tenant_id    IS DISTINCT FROM OLD.tenant_id
            OR NEW.project_id   IS DISTINCT FROM OLD.project_id
            OR NEW.version_id   IS DISTINCT FROM OLD.version_id
            OR NEW.instance_key IS DISTINCT FROM OLD.instance_key
            OR NEW.created_at   IS DISTINCT FROM OLD.created_at THEN
                RAISE EXCEPTION
                    'agent_instances binding columns are immutable '
                    '(tenant_id, project_id, version_id, instance_key, created_at)';
            END IF;
            IF OLD.active_run_id IS NOT NULL
               AND NEW.active_run_id IS DISTINCT FROM OLD.active_run_id THEN
                RAISE EXCEPTION 'agent_instances.active_run_id is set-once (no rebinding)';
            END IF;
            RETURN NEW;
        END
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER agent_instances_block_rebind
            BEFORE UPDATE ON public.agent_instances
            FOR EACH ROW EXECUTE FUNCTION public.agent_instances_block_rebind()
        """
    )

    # --- RLS on the tenant-owned table (mirrors 0002/0004/0005/0006) ----------
    op.execute("ALTER TABLE agent_instances ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE agent_instances FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON agent_instances "
        f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
    )

    # --- privileges -----------------------------------------------------------
    # Global catalog: runtime is READ-ONLY (admin curates).
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON agent_versions FROM PUBLIC")
    op.execute("GRANT SELECT ON agent_blueprints TO uaid_app")
    op.execute("GRANT SELECT ON agent_versions TO uaid_app")
    # Tenant-owned instances: lifecycle needs UPDATE; never DELETE.
    op.execute("GRANT SELECT, INSERT, UPDATE ON agent_instances TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT, UPDATE ON agent_instances FROM uaid_app")
    op.execute("REVOKE SELECT ON agent_versions FROM uaid_app")
    op.execute("REVOKE SELECT ON agent_blueprints FROM uaid_app")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON agent_instances")
    op.execute("ALTER TABLE agent_instances NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE agent_instances DISABLE ROW LEVEL SECURITY")
    op.execute("DROP TRIGGER IF EXISTS agent_instances_block_rebind ON public.agent_instances")
    op.execute("DROP FUNCTION IF EXISTS public.agent_instances_block_rebind()")
    op.execute("DROP TRIGGER IF EXISTS agent_versions_no_truncate ON public.agent_versions")
    op.execute("DROP TRIGGER IF EXISTS agent_versions_no_update_delete ON public.agent_versions")
    op.execute("DROP FUNCTION IF EXISTS public.agent_versions_block_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_agent_instances_live_key",
        table_name="agent_instances",
        postgresql_where=sa.text("status IN ('registered', 'active', 'suspended')"),
    )
    op.drop_index(op.f("ix_agent_instances_tenant_id"), table_name="agent_instances")
    # Drop agent_instances (its triple FK depends on the project_runs unique
    # constraint) BEFORE dropping that constraint.
    op.drop_table("agent_instances")
    op.drop_constraint(
        op.f("uq_project_runs_id_project_id_tenant_id"), "project_runs", type_="unique"
    )
    op.drop_table("agent_versions")
    op.drop_table("agent_blueprints")
    # ### end Alembic commands ###
