"""cost_ledger

Revision ID: 0008
Revises: 0007
Create Date: 2026-06-03

Tenant-owned, IMMUTABLE cost_events (financial ledger: UPDATE/DELETE/TRUNCATE
triggers + REVOKE; uaid_app SELECT/INSERT only) + tenant-owned budgets
(SELECT/INSERT/UPDATE, no DELETE). Both ENABLE+FORCE RLS + tenant_isolation.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("max_total_cost_usd", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("max_daily_cost_usd", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_daily_cost_usd IS NULL OR max_daily_cost_usd >= 0",
            name=op.f("ck_budgets_max_daily_non_negative"),
        ),
        sa.CheckConstraint(
            "max_total_cost_usd >= 0", name=op.f("ck_budgets_max_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_budgets_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint(
            "tenant_id", "project_id", name=op.f("uq_budgets_tenant_id_project_id")
        ),
    )
    op.create_index(op.f("ix_budgets_tenant_id"), "budgets", ["tenant_id"], unique=False)
    op.create_table(
        "cost_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("component", sa.Text(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("source_system", sa.Text(), server_default=sa.text("'internal'"), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component IN ('model_inference', 'tool_execution', 'cloud_runtime', 'ci_cd', "
            "'storage_retrieval', 'monitoring', 'human_review', 'rework')",
            name=op.f("ck_cost_events_component_valid"),
        ),
        sa.CheckConstraint("amount_usd >= 0", name=op.f("ck_cost_events_amount_usd_non_negative")),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity >= 0", name=op.f("ck_cost_events_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id", "tenant_id"],
            ["project_runs.id", "project_runs.project_id", "project_runs.tenant_id"],
            name="run_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_cost_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_events")),
    )
    op.create_index(
        "ix_cost_events_tenant_project", "cost_events", ["tenant_id", "project_id"], unique=False
    )
    op.create_index(
        "ix_cost_events_tenant_project_occurred",
        "cost_events",
        ["tenant_id", "project_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "uq_cost_events_idempotency",
        "cost_events",
        ["tenant_id", "source_system", "external_ref"],
        unique=True,
        postgresql_where=sa.text("external_ref IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # --- cost_events immutability (financial ledger): block UPDATE/DELETE/TRUNCATE.
    # DML-immutable for all roles incl. the table owner; a DB superuser/schema owner
    # can still disable triggers/drop the table (DML-immutable, not tamper-proof).
    op.execute(
        """
        CREATE FUNCTION public.cost_events_block_mutation() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
        BEGIN
            RAISE EXCEPTION 'cost_events is immutable (no UPDATE/DELETE/TRUNCATE)';
        END
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER cost_events_no_update_delete
            BEFORE UPDATE OR DELETE ON public.cost_events
            FOR EACH ROW EXECUTE FUNCTION public.cost_events_block_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER cost_events_no_truncate
            BEFORE TRUNCATE ON public.cost_events
            FOR EACH STATEMENT EXECUTE FUNCTION public.cost_events_block_mutation()
        """
    )

    # --- RLS (mirrors 0002/0004/0005/0006/0007) on both tenant-owned tables -----
    for table in ("cost_events", "budgets"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
        )

    # --- privileges -----------------------------------------------------------
    # cost_events: append-only financial ledger (no UPDATE/DELETE/TRUNCATE).
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON cost_events FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT ON cost_events TO uaid_app")
    # budgets: ceilings adjust over time (audited); never DELETE.
    op.execute("GRANT SELECT, INSERT, UPDATE ON budgets TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT, UPDATE ON budgets FROM uaid_app")
    op.execute("REVOKE SELECT, INSERT ON cost_events FROM uaid_app")
    for table in ("cost_events", "budgets"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    op.execute("DROP TRIGGER IF EXISTS cost_events_no_truncate ON public.cost_events")
    op.execute("DROP TRIGGER IF EXISTS cost_events_no_update_delete ON public.cost_events")
    op.execute("DROP FUNCTION IF EXISTS public.cost_events_block_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_cost_events_idempotency",
        table_name="cost_events",
        postgresql_where=sa.text("external_ref IS NOT NULL"),
    )
    op.drop_index("ix_cost_events_tenant_project_occurred", table_name="cost_events")
    op.drop_index("ix_cost_events_tenant_project", table_name="cost_events")
    op.drop_table("cost_events")
    op.drop_index(op.f("ix_budgets_tenant_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
