"""workflow_runtime

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-03 22:50:48.139854

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_checkpoint_writes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("checkpoint_ns", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("checkpoint_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.Column("task_path", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "thread_id = run_id::text", name=op.f("ck_run_checkpoint_writes_thread_matches_run")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id", "tenant_id"],
            ["project_runs.id", "project_runs.project_id", "project_runs.tenant_id"],
            name="run_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_run_checkpoint_writes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_checkpoint_writes")),
        sa.UniqueConstraint(
            "tenant_id",
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name="uq_run_checkpoint_writes_id",
        ),
    )
    op.create_index(
        "ix_run_checkpoint_writes_cp",
        "run_checkpoint_writes",
        ["tenant_id", "thread_id", "checkpoint_ns", "checkpoint_id"],
        unique=False,
    )
    op.create_table(
        "run_checkpoints",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("checkpoint_ns", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("checkpoint_id", sa.Text(), nullable=False),
        sa.Column("parent_checkpoint_id", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("checkpoint", sa.LargeBinary(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "thread_id = run_id::text", name=op.f("ck_run_checkpoints_thread_matches_run")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id", "tenant_id"],
            ["project_runs.id", "project_runs.project_id", "project_runs.tenant_id"],
            name="run_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_run_checkpoints_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_checkpoints")),
        sa.UniqueConstraint(
            "tenant_id", "thread_id", "checkpoint_ns", "checkpoint_id", name="uq_run_checkpoints_id"
        ),
    )
    op.create_index(
        "ix_run_checkpoints_thread",
        "run_checkpoints",
        ["tenant_id", "thread_id", "checkpoint_ns"],
        unique=False,
    )
    op.create_table(
        "run_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node", sa.Text(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("status_from", sa.Text(), nullable=True),
        sa.Column("status_to", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('run_started', 'step_completed', 'run_resumed', 'run_completed', 'run_failed')",
            name=op.f("ck_run_steps_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id", "tenant_id"],
            ["project_runs.id", "project_runs.project_id", "project_runs.tenant_id"],
            name="run_project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_run_steps_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
    )
    op.create_index(
        "ix_run_steps_run_seq", "run_steps", ["tenant_id", "run_id", "seq"], unique=False
    )
    # ### end Alembic commands ###

    # --- run_steps immutability (append-only history): block UPDATE/DELETE/TRUNCATE.
    # DML-immutable for all roles incl. the table owner; a DB superuser can still
    # disable triggers/drop the table (DML-immutable, not tamper-proof).
    op.execute(
        """
        CREATE FUNCTION public.run_steps_block_mutation() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
        BEGIN
            RAISE EXCEPTION 'run_steps is immutable (no UPDATE/DELETE/TRUNCATE)';
        END
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER run_steps_no_update_delete
            BEFORE UPDATE OR DELETE ON public.run_steps
            FOR EACH ROW EXECUTE FUNCTION public.run_steps_block_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER run_steps_no_truncate
            BEFORE TRUNCATE ON public.run_steps
            FOR EACH STATEMENT EXECUTE FUNCTION public.run_steps_block_mutation()
        """
    )

    # --- RLS on all three tenant-owned tables (mirrors prior slices) -----------
    _predicate = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    for table in ("run_checkpoints", "run_checkpoint_writes", "run_steps"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_predicate}) WITH CHECK ({_predicate})"
        )

    # --- privileges -----------------------------------------------------------
    # Checkpoint tables = mutable working state (checkpointer + adelete_thread).
    op.execute("GRANT SELECT, INSERT, DELETE ON run_checkpoints TO uaid_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON run_checkpoint_writes TO uaid_app")
    # run_steps = immutable append-only history.
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON run_steps FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT ON run_steps TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT ON run_steps FROM uaid_app")
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON run_checkpoint_writes FROM uaid_app")
    op.execute("REVOKE SELECT, INSERT, DELETE ON run_checkpoints FROM uaid_app")
    for table in ("run_checkpoints", "run_checkpoint_writes", "run_steps"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    op.execute("DROP TRIGGER IF EXISTS run_steps_no_truncate ON public.run_steps")
    op.execute("DROP TRIGGER IF EXISTS run_steps_no_update_delete ON public.run_steps")
    op.execute("DROP FUNCTION IF EXISTS public.run_steps_block_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_steps_run_seq", table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index("ix_run_checkpoints_thread", table_name="run_checkpoints")
    op.drop_table("run_checkpoints")
    op.drop_index("ix_run_checkpoint_writes_cp", table_name="run_checkpoint_writes")
    op.drop_table("run_checkpoint_writes")
    # ### end Alembic commands ###
