"""documents

Revision ID: 0011
Revises: 0010
Create Date: 2026-06-04 10:49:11.554018

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "scan_result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_documents_content_hash_format")
        ),
        sa.CheckConstraint(
            "content_type IN ('text/plain', 'text/markdown')",
            name=op.f("ck_documents_content_type_allowed"),
        ),
        sa.CheckConstraint(
            "source IN ('customer_upload', 'api_ingest', 'manual')",
            name=op.f("ck_documents_source_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('accepted', 'quarantined')", name=op.f("ck_documents_status_valid")
        ),
        sa.CheckConstraint(
            "octet_length(content) BETWEEN 1 AND 1048576", name=op.f("ck_documents_content_bounded")
        ),
        sa.CheckConstraint(
            "octet_length(filename) BETWEEN 1 AND 255", name=op.f("ck_documents_filename_bounded")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_documents_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="project_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_documents_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("tenant_id", "project_id", "content_hash", name="uq_documents_content"),
    )
    op.create_index(
        "ix_documents_tenant_project", "documents", ["tenant_id", "project_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- combined guard: content integrity (INSERT) + immutability & one-way
    #     status lifecycle (UPDATE). Core sha256 (no extension; mirrors 0003).
    op.execute(
        """
        CREATE FUNCTION public.documents_guard() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
        BEGIN
            IF TG_OP = 'INSERT' THEN
                IF octet_length(NEW.content) NOT BETWEEN 1 AND 1048576 THEN
                    RAISE EXCEPTION 'documents.content size out of range';
                END IF;
                IF NEW.size_bytes <> octet_length(NEW.content) THEN
                    RAISE EXCEPTION 'documents.size_bytes must equal octet_length(content)';
                END IF;
                IF NEW.content_hash <> 'sha256:' || encode(sha256(convert_to(NEW.content, 'UTF8')), 'hex') THEN
                    RAISE EXCEPTION 'documents.content_hash does not match content';
                END IF;
                RETURN NEW;
            END IF;
            -- UPDATE: content/identity columns are immutable.
            IF NEW.content      IS DISTINCT FROM OLD.content
            OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
            OR NEW.size_bytes   IS DISTINCT FROM OLD.size_bytes
            OR NEW.tenant_id    IS DISTINCT FROM OLD.tenant_id
            OR NEW.project_id   IS DISTINCT FROM OLD.project_id
            OR NEW.source       IS DISTINCT FROM OLD.source
            OR NEW.filename     IS DISTINCT FROM OLD.filename
            OR NEW.content_type IS DISTINCT FROM OLD.content_type
            OR NEW.created_at   IS DISTINCT FROM OLD.created_at THEN
                RAISE EXCEPTION 'documents content/identity columns are immutable';
            END IF;
            -- one-way status lifecycle: only accepted -> quarantined (or no-op).
            IF NEW.status <> OLD.status
               AND NOT (OLD.status = 'accepted' AND NEW.status = 'quarantined') THEN
                RAISE EXCEPTION 'documents.status transition % -> % not allowed',
                    OLD.status, NEW.status;
            END IF;
            RETURN NEW;
        END
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER documents_guard
            BEFORE INSERT OR UPDATE ON public.documents
            FOR EACH ROW EXECUTE FUNCTION public.documents_guard()
        """
    )

    # --- RLS (mirrors prior tenant-owned tables) ------------------------------
    _predicate = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"
    op.execute("ALTER TABLE documents ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE documents FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON documents "
        f"USING ({_predicate}) WITH CHECK ({_predicate})"
    )

    # --- privileges: lifecycle needs UPDATE; never DELETE ---------------------
    op.execute("GRANT SELECT, INSERT, UPDATE ON documents TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT, INSERT, UPDATE ON documents FROM uaid_app")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON documents")
    op.execute("ALTER TABLE documents NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE documents DISABLE ROW LEVEL SECURITY")
    op.execute("DROP TRIGGER IF EXISTS documents_guard ON public.documents")
    op.execute("DROP FUNCTION IF EXISTS public.documents_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_tenant_project", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
