"""tenant_api_keys

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-04 14:10:02.650623

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_api_keys",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default=sa.text("'active'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_tenant_api_keys_key_hash_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_tenant_api_keys_status_valid")
        ),
        sa.CheckConstraint(
            "octet_length(label) BETWEEN 1 AND 255", name=op.f("ck_tenant_api_keys_label_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_api_keys_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_tenant_api_keys_key_hash")),
    )
    op.create_index("ix_tenant_api_keys_tenant", "tenant_api_keys", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # GLOBAL auth-lookup table — intentionally NOT RLS (resolution happens before any
    # tenant is known, so it must be readable without the app.current_tenant GUC).
    # Admin issues/revokes; the runtime role gets SELECT only (resolve by hash).
    # Mirrors the organizations/tenants grant pattern (migration 0002).
    op.execute("GRANT SELECT ON tenant_api_keys TO uaid_app")


def downgrade() -> None:
    op.execute("REVOKE SELECT ON tenant_api_keys FROM uaid_app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenant_api_keys_tenant", table_name="tenant_api_keys")
    op.drop_table("tenant_api_keys")
    # ### end Alembic commands ###
